In [2228]:
# import cosine
# import jaccard
# import numpy as np
# import pandas as pd
# import clean_text_regex

In [2229]:
# df = pd.read_csv("C:\\Users\\bOct0\\OneDrive - vit.ac.in\\Web mining\\python\\Dataset\\Training.csv")
# df = pd.DataFrame(columns=['stop_count_original','stop_count_plagiarized','punctuation_count_original','plagiarized_punctuation_count','word_overlap','cosine','jaccard','euclidean_distance','levenshtein'])

In [2230]:
#original
content = '''
Sure, here's another example of plagiarized content:

Original content: The Declaration of Independence was signed on July 4, 1776, in Philadelphia, Pennsylvania, by 56 delegates to the Continental Congress.

Plagiarized content: In Philadelphia, Pennsylvania, on July 4, 1776, 56 delegates to the Continental Congress signed the Declaration of Independence.
'''#plagiarized
copied = '''
Climate change is a pressing global issue that is causing significant changes to the Earth's weather patterns, natural ecosystems, and human societies. The primary cause of climate change is the increase in atmospheric concentrations of greenhouse gases, such as carbon dioxide, methane, and nitrous oxide, due to human activities such as burning fossil fuels, deforestation, and agriculture. The consequences of climate change are already being felt, with rising sea levels, more frequent and severe natural disasters, and shifts in agricultural productivity. Urgent action is needed to mitigate the effects of climate change and adapt to the changes that are already occurring.
 '''# print(len(content))

In [2231]:
row = []

In [2232]:
#stop word count
original_stopword_count = clean_text_regex.stopwordcount(content)
plagiarized_stopword_count = clean_text_regex.stopwordcount(copied)
#append to df
row.append(original_stopword_count)
row.append(plagiarized_stopword_count)

In [2233]:
#punctuation count
original_punctuation_count = clean_text_regex.punctuation_count(content)
plagiarized_punctuation_count = clean_text_regex.punctuation_count(copied)
#append to df
row.append(original_punctuation_count)
row.append(plagiarized_punctuation_count)

In [2234]:
#text after punctuation removal, stop word removal, numbers removal and extra whitespace removal
content = clean_text_regex.clean_text(content)
copied = clean_text_regex.clean_text(copied)
# print(content)

In [2235]:
#separating original content from plagiarized content
original,plagiarized = content,copied
# print(original)
# print(plagiarized)

In [2236]:
#word overlap ratio
import wordoverlapratio
row.append(wordoverlapratio.word_overlap_ratio(original,plagiarized))
# wordoverlapratio.word_overlap_ratio('hell','wate')
# df

0.0

In [2237]:
#cosine similarity
import cosine
row.append(cosine.cosine_similarity(original,plagiarized))

In [2238]:
#jaccard similarity
import jaccard
row.append(jaccard.jaccard_similarity(original,plagiarized))

In [2239]:
#euclidean distance
import euclidean_distance
row.append(euclidean_distance.euclidean(original,plagiarized))

In [2240]:
#Levenshtein Distance
import levenshtein
row.append(levenshtein.levenshtein_distance(original,plagiarized))

In [2241]:
#sentence length
# df
# len(df)
# co = int(input())
# row.append(co)
df.loc[len(df)]=row
# len(row)

In [2242]:
# row = []

In [2243]:
df

,stop_count_original,stop_count_plagiarized,punctuation_count_original,plagiarized_punctuation_count,word_overlap,cosine,jaccard,euclidean_distance,levenshtein
0,30.0,67.0,5.0,15.0,0.586207,0.490330,0.298246,9.000000,289.0
1,31.0,30.0,5.0,9.0,0.404255,0.612538,0.327586,7.416198,206.0
2,60.0,31.0,12.0,5.0,0.037975,0.294431,0.042857,16.370706,416.0
3,30.0,60.0,9.0,12.0,0.041667,0.232826,0.026316,16.703293,421.0
4,119.0,86.0,56.0,43.0,0.107143,0.241747,0.091371,21.447611,905.0
...,...,...,...,...,...,...,...,...,...
100,172.0,167.0,50.0,59.0,0.194444,0.419005,0.219731,29.206164,1504.0
101,706.0,134.0,310.0,77.0,0.111876,0.860709,0.305164,69.512589,7308.0
102,27.0,11.0,11.0,14.0,0.095238,0.288210,0.095238,9.848858,250.0
103,15.0,38.0,15.0,16.0,0.000000,0.000000,0.000000,12.649111,389.0
104,15.0,38.0,15.0,16.0,0.000000,0.000000,0.000000,12.649111,389.0

In [2244]:
df.to_excel('train.xlsx')

In [2245]:
#import dataset
import pandas as pd
df = pd.read_excel('train.xlsx')
df

,Unnamed: 0,stop_count_original,stop_count_plagiarized,punctuation_count_original,plagiarized_punctuation_count,word_overlap,cosine,jaccard,euclidean_distance,levenshtein
0,0,30,67,5,15,0.586207,0.490330,0.298246,9.000000,289
1,1,31,30,5,9,0.404255,0.612538,0.327586,7.416198,206
2,2,60,31,12,5,0.037975,0.294431,0.042857,16.370706,416
3,3,30,60,9,12,0.041667,0.232826,0.026316,16.703293,421
4,4,119,86,56,43,0.107143,0.241747,0.091371,21.447611,905
...,...,...,...,...,...,...,...,...,...,...
100,100,172,167,50,59,0.194444,0.419005,0.219731,29.206164,1504
101,101,706,134,310,77,0.111876,0.860709,0.305164,69.512589,7308
102,102,27,11,11,14,0.095238,0.288210,0.095238,9.848858,250
103,103,15,38,15,16,0.000000,0.000000,0.000000,12.649111,389
104,104,15,38,15,16,0.000000,0.000000,0.000000,12.649111,389